### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by PalePyth** [Abastro/StellarSky#10]
Good idea, man. But when I use your mod (1.7.10) my FPS is over 10! But regular I have 60 FPS. Can you do something with it?

**Comment by Abastro** [comment]
I'd fix the FPS problem, maybe on next version.
It will be major change.

**Comment by PalePyth** [comment]
Could you say when are you going to release it?

**Comment by Abastro** [comment]
It would take a month, I think.

**Comment by PitchBright** [comment]
@PalePyth post your stellarsky.cfg file in a pastebin link please.

**Comment by PalePyth** [comment]
http://pastebin.com/wFB399AE

**Comment by PitchBright** [comment]
Did you try lowering your MagLimit to increase your FPS like it says in the description?

**Comment by PalePyth** [comment]
Can you do 0.3 MagLimit by default? Please. My server doesn't give this config to clients for some reason. And the config creates with 5.0.

**Comment by PitchBright** [comment]
did it work… or?

**Comment by PitchBright** [comment]
btw… that's a clientside option. Meaning… every user will want to tailor it to suit their own needs/preferences. (Just like you wouldn't want a server setting your optifine settings, as a player.)

If you want to avoid having to play IT guy for your servers users… distribute a pre-crafted client config for you modpack.

**Comment by PitchBright** [comment]
@PalePyth please close this issue if your problem is solved.

**Comment by PalePyth** [comment]
My problem isn't solved. Usually mods load their configs from the config folder in my launcher. But your mod doesn't it. I would like you release the light version with 0.3 by default.

**Comment by PitchBright** [comment]
Use a text editor to change the config.

**Comment by PitchBright** [comment]
For the clients using the mod, they'll have to edit their configs to suit their tastes as well. Just because you're getting FPS drop at 5.0 doesn't mean they will. Everybody's computer is different.

**Comment by PitchBright** [comment]
The reason it doesn't give the setting to clients, is because that setting is a Client-Side "preference". Would you want Mojang to make it so that servers can force you to use certain keys for Run, Jump, Sprint, Sneak?? Of course not. Same with this mod, it's up to each user to set their own preferences.

This is not an issue or a problem with the mod, you can Close it now.

**Comment by Abastro** [comment]
closing this issue since OP don't know how

**Comment by Abastro** [comment]
..to set up configs on client for modpacks.
I'll do improve FPS on next version.

**Comment by PitchBright** [comment]
If he was using modpacks, then I'm not sure what his problem is. All he has to do is ship the config edited the way he wants clients to get it, in the modpack itself. I think he doesn't know how to edit a config file, and so he wants you to change your mod so he doesn't have to learn how.

Also… MagLimit of 0.3 is so low that you can only see half a dozen stars. If he sets it to 0.3, he might as well not even use the mod, because it would be pointless to have a star mod that doesn't show any stars.
