### ISSUE TITLE
[Suggestion] Light Polution

### ISSUE THREAD

**Issue by dexman545** [Abastro/StellarSky#28]
Dynamically changing the Mag limit dependent on block light level would simulate light pollution. Just a neat idea a friend had.

**Comment by PitchBright** [comment]
I think a better way to do it would be to scan surrounding chunks to count the number of blocks > x light level, and then adjust the visibility of the stars (client-side) that way. Only because a single block's light level, really shouldn't be enough to cause 'light pollution', on it's own.. "technically".

**Comment by Abastro** [comment]
@PitchBright The light level of certain block is already calculated based on light levels of blocks around the block. So it doesn't matter.

**Comment by Abastro** [comment]
(Mistake;)

**Comment by Abastro** [comment]
Implemented on recent versions.
(On 1.7.10, commit df6cd8307aad660698cbdbcbea6ab337f863536f did that)
