### ISSUE TITLE
crashed instantly after logged on server 1.10.2

### ISSUE THREAD

**Issue by sofifreak** [Abastro/StellarSky#83]
I added the mod to our modpack for testing. 
Without Custom Mob Spawner (CustomMobSpawner 3.10.1) it works
within it crashed

[crash-2017-06-06_13.23.46-client.txt](https://github.com/Abastro/StellarSky/files/1055028/crash-2017-06-06_13.23.46-client.txt)

i don´t know why?

**Comment by PitchBright** [comment]
@sofifreak Use www.pastebin.com to paste your crashreports. Nobody wants to download something, if they aren't sure what it is they're downloading. (Viruses, Trojans, etc).

The crash says the problem is Custom Mob Spawner:

`
java.lang.NullPointerException: Ticking entity
	at drzhark.customspawner.EventHooks.onLivingDespawn(EventHooks.java:142)
`

The problem Entity is your Pig named "Schwein":

`
-- Entity being ticked --
Details:
	Entity Type: Pig (net.minecraft.entity.passive.EntityPig)
	Entity ID: 1231
	Entity Name: Schwein
`

There's nothing about this crash report at first glance that makes it look like Stellar Sky is at fault.

How often does this exact crash occur?

**Comment by sofifreak** [comment]
The crash happened every time I logged in.
When i remove the Mo Creature and Mobspawner Mod it works. And differently when i remove the Stellar Sky mod it works too. 

I thought I just ask on something such is known.
I opend an issues at the Mob Spawner Mod too

I found the Stellar Sky mod at cruseforge and he is awesome.

**Comment by Abastro** [comment]
Can't diagnose this issue from here(Stellar Sky).
Please contact author(s) of Custom Mob Spawner.

**Comment by Abastro** [comment]
No response for weeks, closing this now.
